README.md, Sources/CreateAPI/GenerateOptions.swift, Sources/CreateAPI/Generator/Generator+Schemas.swift
Hello :)
While implementing this plugin into our project, I found that `Entities.skip` is very hard to maintain.
Therefore, I'd like to implement `include` which works completely opposite way from `skip`.
We are currently just replacing hard-coded entities with CreateAPI generated entities, but of course, it is difficult to replace hundreds of entities at once. Therefore, we plan to replace them gradually. In this context, `include` is much more useful than `skip`.
- Renamed `skip` to `exclude` to provide a kind of consistency with `include`. If you have any other suggestions, please :)
- Added `include`
- Throw error when both of `include` and `exclude` have value.
=> Add Entities.include

Sources/CreateAPI/GenerateOptions.swift
This reverts commit 324ab3e6f87d6204571204332f7ca6270c10d79d.
[Former PR](https://github.com/kean/CreateAPI/pull/5) contained unintentional change which I was working on different PR. Sorry 😢
=> Revert "Added entityPrefix and entitySuffix to GenerateOptions.Rename"

Sources/CreateAPI/Generator/Generator+Schemas.swift
> Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.
> — [Specification](https://swagger.io/specification/)
The builtin UUID type is already `Codable`, so unless I'm missing something this should just work. 
```swift
import Foundation
struct Model: Codable {
let id: UUID
}
let json = """
{
"id": "f44d74e7-a8ca-4d5d-9d7d-6b28fc28b552"
}
"""
let decoder = JSONDecoder()
let decoded = try! decoder.decode(Model.self, from: json.data(using: .utf8)!)
let encoder = JSONEncoder()
let encodedData = try! encoder.encode(decoded)
let encodedString = String(data: encodedData, encoding: .utf8)
```
=> Use builtin `UUID` type for `uuid` format in schemas

Sources/CreateAPI/Generator/Declarations.swift, Sources/CreateAPI/Generator/Generator+Render.swift, Sources/CreateAPI/Generator/Generator+Schemas.swift, Sources/CreateAPI/Generator/Templates.swift, Tests/CreateAPITests/Expected/discriminator/Sources/Entities.swift, Tests/CreateAPITests/GenerateTests.swift, Tests/CreateAPITests/Specs/discriminator.yaml
Adds initial support for decoding `oneOf` entities with a [discriminator](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) attribute.
Using the existing property type name machinery when constructing the discriminator is still outstanding. 
Would really appreciate some help with that, because I struggled to find a clean way to call into one of the name canonicalization functions.
<details>
<summary>Generated Code</summary>
```swift
public struct A: Codable {
public var kind: String
public init(kind: String) {
self.kind = kind
}
}
public struct B: Codable {
public var kind: String
public init(kind: String) {
self.kind = kind
}
}
public struct C: Codable {
public var kind: String
public init(kind: String) {
self.kind = kind
}
}
public struct Container: …
```
=> Discriminator Support

Sources/CreateAPI/Generator/Generator+Schemas.swift
While testing the upstream changes, entities defined in `entities.include` were skipped. I noticed `shouldGenerate` for entities option doesn't look right. I suppose it should have checked `options.entities.include` instead of `options.path.include` in `Generator+Schemas.swift`.
You can test it with any configurations that have `entities.include`. I believe entities defined in `entities.include` should not be skipped.
```yml
entities:
isGeneratingStructs: true
isGeneratingMutableStructProperties: false
include:
User
```
=> Fix shouldGenerate check for entities.include option

Sources/CreateAPI/Generator/Generator+Schemas.swift
When the spec defines a string property with a byte format at the moment a `String` property is generated, but a `Data` property should  be generated instead.
With input:
```yaml
test_property:
type: string
format: byte
```
Before:
```swift
var testProperty: String
```
After:
```swift
var testProperty: Data
```
=> Fix `String` type with `byte` format

Sources/CreateAPI/Generator/Declarations.swift, Sources/CreateAPI/Generator/Generator+Render.swift, Sources/CreateAPI/Generator/Templates.swift, Tests/CreateAPITests/Expected/discriminator/Sources/Entities.swift, Tests/CreateAPITests/Specs/discriminator.yaml
Currently, CreateAPI only supports a unique type for each mapping case.
For example, if we have
```yml
Container:
type: object
required:
- content
properties:
content:
oneOf:
- $ref: "#/components/schemas/A"
- $ref: "#/components/schemas/B"
- $ref: "#/components/schemas/C"
discriminator:
propertyName: kind
mapping:
a: "#/components/schemas/A"
b: "#/components/schemas/B"
c: "#/components/schemas/C"
d: "#/components/schemas/A"
```
it only generates `.a` but `.d` is not generated.
This is because we only use the first case with the property type.
https://github.com/CreateAPI/CreateAPI/blob/a59c76632f3199ddb016447dc04ceb83102d3f61/Sources/CreateAPI/Generator/Templates.swift#L314
In this PR, I have fixed the issue above by checking the `mapping` keys and updated the discriminator test case for …
=> Support multiple discriminator mappings to share one type

.github/workflows/ci.yml, Scripts/test-generated.sh
Prior to this change, the CI checks ran using only a single version of Xcode (and Swift). 
This change updates the workflow to use a matrix of different Xcode versions meaning that we get coverage with both the Swift 5.5 and 5.6 compiler.
=> Update GitHub Workflow CI

Sources/CreateAPI/Generator/Declarations.swift, Sources/CreateAPI/Generator/Generator+Render.swift, Sources/CreateAPI/Generator/Generator+Schemas.swift, Tests/CreateAPITests/Expected/edgecases-change-access-control/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-coding-keys/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-default/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-disable-acronyms/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-disable-enums/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-indent-with-two-width-spaces/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-int32-int64/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-rename-properties/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-rename/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-tabs/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-yaml-config/Sources/Entities.swift, Tests/CreateAPITests/Specs/edgecases.yaml
When we have this kind OpenAPI schema ↓
```JSON
"Dog": {
"allOf": [
{
"type": "object",
"additionalProperties": false,
"required": ["type"],
"properties": {
"type": {
"type": "string",
"enum": ["dog"]
}
}
},
{
"$ref": "#/components/schemas/BaseDog"
}
]
}
```
it fails to decode `type` because currently, CreateAPI generates ↓
``` Swift
public init(from decoder: Decoder) throws {
self.type = try `Type`(from: decoder) # ← THIS IS WRONG
self.baseDog = try BaseDog(from: decoder)
}
```
It should be
```Swift
public init(from decoder: Decoder) throws {
let values = try decoder.container(keyedBy: StringCodingKey.self)
self.type = try values.decode(`Type`.self, forKey: "type") # ← THIS IS CORRECT
self.baseDog = try BaseDog(from: decoder)
}
```
In this PR, I've added `isInlineed` to `Property` in …
=> Fix allOf decoding issue

Sources/CreateAPI/Generator/Templates.swift, Tests/CreateAPITests/Expected/edgecases-change-access-control/Sources/Entities.swift, Tests/CreateAPITests/Expected/edgecases-change-access-control/Sources/Paths.swift
closes #32 
While we do `lhs.joined(separator: " ")` and sometimes have `""` for the access level, it inserts unnecessary space before `struct` and `class` declaration.
Remove the redundant space.
- Filtering `""` too, not only `nil`.
- Fixed tests
=> Removed redundant space before struct and class declaration

Sources/CreateAPI/CreateAPI.swift
> [SE-0281](https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md) introduced a new `@main` attribute to allow us to declare where the entry point for a program is. This allows us to control exactly which part of our code should start running, which is particularly useful for command-line programs.
https://www.hackingwithswift.com/swift/5.3/atmain
It's only a small improvement, but since CreateAPI supports Swift 5.5 and above, we might as well take advantage of it
=> Remove main.swift and mark CreateAPI as @main type directly

Sources/CreateAPI/Generator/Templates.swift, Tests/CreateAPITests/Expected/cookpad/Sources/Entities.swift, Tests/CreateAPITests/Expected/discriminator/Sources/Entities.swift, Tests/CreateAPITests/Specs/cookpad.json, Tests/CreateAPITests/Specs/discriminator.yaml
- Closes #44
It was reported that when a string that is used in comments uses `\r` for line breaks, the generated code will incorrectly fail to prefix the line with `///` resulting in non-compiling source files.
From what I could tell, the easiest way to fix this is to separate into components based on anything within the predefined `.newlines` `CharacterSet`. 
It was a bit tricky to do this using `firstIndex(of:)` in the existing while loop, whereas it was much easier to use `components(separatedBy:)`. However, I am wary because of this comment:
```swift
// Unlike `components(separatedBy: "\n")`, it keeps empty lines.
```
However when I compared the implementation, I didn't see a difference in output:
@kean, please could you confirm if I missed anything here? It looks like it works as …
=> Fix comment generation when using other kind of linebreaks

Tests/CreateAPITests/Snapshots.swift
`#filePath` is the closest we can get in regards to "automatic file path finding".
=> Tests - Automatic Path Finding and Remove Environment Variables

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, Scripts/artifactbundle.sh
- #48 
When creating and using Swift Package plugins, there are a couple of ways that you can approach it:
1. The vendor (or even the consumer) can use the executable's package as a dependency
2. The consume can add their own `.binaryTarget` dependency 
The second option is great when you don't want to have to concern yourself with potentially complex build pipelines for the build tools given that usually we work with precompiled binaries.
To do this, the vendor needs to provide an artifactbundle as described in [SE-[0305](https://github.com/apple/swift-evolution/blob/main/proposals/0305-swiftpm-binary-target-improvements.md)](https://github.com/apple/swift-evolution/blob/main/proposals/0305-swiftpm-binary-target-improvements.md).
In this Pull Request, I do a few things to introduce the …
=> Produce an artifactbundle when making releases 

Docs/ConfigOptions.md, Sources/CreateAPI/Generator/Generator+Paths.swift, Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift, Sources/CreateOptions/ConfigOptions.swift, Sources/CreateOptions/GenerateOptions.swift, Tests/CreateAPITests/GenerateTests.swift, Tests/CreateOptionsTests/GenerateOptionsTests.swift
- #77 
I came across a typo in the two 'overriden' config options in `paths` (missing an extra `d`). We want to rename it, but we have to be cautious that some people might have this property in their config file.
In this change, I rename the property, but keep the old one around as 'deprecated' so that we don't break any current usage and instead emit a warning when running the tool
> WARNING: The property 'paths.overridenResponses' has been deprecated. Renamed to 'overriddenResponses'.
=> Rename `overridenResponses` to `overriddenResponses` and `overridenBodyTypes` to `overriddenBodyTypes`

LICENSE, Sources/CreateAPI/CreateAPI.swift, Sources/CreateAPI/Generate.swift, Sources/CreateAPI/Generator/Declarations.swift, Sources/CreateAPI/Generator/Generator+Package.swift, Sources/CreateAPI/Generator/Generator+Paths.swift, Sources/CreateAPI/Generator/Generator+Render.swift, Sources/CreateAPI/Generator/Generator+Schemas.swift, Sources/CreateAPI/Generator/Generator.swift, Sources/CreateAPI/Generator/Naming.swift, Sources/CreateAPI/Generator/Templates.swift, Sources/CreateAPI/Helpers/Files.swift, Sources/CreateAPI/Helpers/Helpers.swift, Sources/CreateAPI/Helpers/OpenAPI+Extensions.swift, Sources/CreateAPI/Helpers/ParallelDocumentParser.swift, Sources/CreateAPI/Helpers/Watcher.swift, Tests/CreateAPITests/GenerateBaseTests.swift, Tests/CreateAPITests/GenerateFeaturesTests.swift, Tests/CreateAPITests/GenerateOptionsTests.swift, Tests/CreateAPITests/GenerateTests.swift, Tests/CreateAPITests/Helpers.swift, Tests/CreateAPITests/HelpersTests.swift, Tests/CreateAPITests/Snapshots.swift
- #69 
To publish to Homebrew, all projects must have a license and I noticed that most repos in the CreateAPI org were missing one. I'm following what HTTPHeaders uses and going with MIT. 
If you are ok with this @kean, I'll go ahead and just push the file directly to the other repos rather than creating Pull Requests for each one.
=> Add LICENSE

Sourcery/DecodableWithDefault.swift.stencil, Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift, Sources/CreateOptions/IssueRecorder.swift, Sources/CreateOptions/StringCodingContainer.swift, Tests/CreateOptionsTests/StringCodingContainerTests.swift
In #77 we started emitting warnings for unknown properties that were found in the config options as well as deprecations:
> WARNING: The property 'overridenResponses' (in 'paths') has been deprecated. Renamed to 'overriddenResponses'.
> WARNING: Found an unexpected property 'unknownProperty'.
While the deprecations are useful, to begin with we are going to be a bit more aggressive and skip deprecating types meaning that when upgrading from 0.0.5 to 0.1.0, you'll end up seeing warnings like "Found an unexpected property 'overridenResponses' (in 'paths')."
This might initially be confusing to the user since it use to work. The aim of this change is to tweak the messaging to better support direct replacements without deprecation.
With this change, a user defining `overridenResponses` in the …
=> Produce better warnings when using configuration options that have been removed

Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift, Sources/CreateOptions/ConfigOptions.swift, Sources/CreateOptions/GenerateOptions.swift, Tests/CreateOptionsTests/GenerateOptionsTests.swift
For 0.1.0 we're going be a bit more aggressive so instead of deprecating properties in the configuration file, we're just going to directly remove support for them meaning that there will instead be migration steps involved.
In #78, I replaced `overridenResponses` and `overridenBodyTypes` with properties that corrected the typos and with that I marked the old ones as deprecated and made sure that they continued to work. Now however, I'm just removing them.
This means that in 0.1.0 the user will have to fix this typo themselves if they are using the properties in their configuration. 
## Release Note
- The `paths.overridenResponses` property has been renamed to `paths.overriddenResponses`
- The `paths.overridenBodyTypes` property has been renamed to `paths.overriddenBodyTypes`
=> Remove deprecated `overridenResponses` and `overridenBodyTypes` properties

Docs/ConfigOptions.md, Sources/CreateAPI/Generator/Generator+Schemas.swift, Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift, Sources/CreateOptions/ConfigOptions.swift
- Closes #93 
If I understand the schema correctly, we don't need to worry about `additionalProperties` meaning anything other than `true` when it's not specified because this is documented in the OpenAPI spec:
> - `additionalProperties` - Value can be boolean or object. Inline or referenced schema MUST be of a [Schema Object](https://swagger.io/specification/#schema-object) and not a standard JSON Schema. **Consistent with JSON Schema, `additionalProperties` defaults to `true`.**
This would mean that `isAdditionalPropertiesOnByDefault` is redundant. Therefore I am removing it and making it's behaviour when `true` the default.
=> Remove `isAdditionalPropertiesOnByDefault` 

Docs/ConfigOptions.md, Sources/CreateAPI/Generator/Naming.swift, Sources/CreateOptions/ConfigOptions+DecodableWithDefault.swift, Sources/CreateOptions/ConfigOptions.swift, Sources/CreateOptions/GenerateOptions.swift, Tests/CreateAPITests/GenerateOptionsTests.swift, Tests/CreateAPITests/HelpersTests.swift
- Closes #97 
Prior to this change, there were three different options for managing acronyms. One to enable/disable and another two to add/ignore to/from the default list. 
In this change, I consolidate these three options into a single `acronyms` option. To disable replacement, you set it to an empty array but to modify it, you just maintain complete list yourself.
=> Consolidate acronym related options into single `acronyms` option

Sources/CreateAPI/Generate.swift, Sources/CreateAPI/Generator/Generator+Package.swift, Sources/CreateAPI/Output/Output.swift, Sources/CreateAPI/Output/OutputWriter.swift
- #116 
- #88 
In some upcoming changes I want to make adjustments to the logic around writing outputs but I had a bit of a hard time with the way things were currently written. For that reason, I think it was time for a bit of a cleanup 🙂 
In this change, I bring in two new types:
1. `OutputWriter`, a small and generic class that helps make it easy to write files out into various directory structures. It's completely generic and not tied to any generator implementation details and does a few other things like throw errors if you try writing a file to the same location twice.
2. `Output`, basically a wrapper around the two `GeneratorOutput`'s that also includes the generated Package.swift manifest and the relevant `GenerateOptions`. It provides a nice isolated location for us the new …
=> Refactor responsibility of writing generated output out of `Generate` command

Tests/CreateAPITests/GenerateBaseTests.swift, Tests/CreateAPITests/GenerateFeaturesTests.swift, Tests/CreateAPITests/GenerateOptionsTests.swift, Tests/CreateAPITests/GenerateTestCase.swift, Tests/CreateAPITests/GenerateTests.swift
- related #88 
Prior to now, the tests would generate and assert snapshots in a relatively verbose way which gets tricky around file paths. This would make my job harder when adjusting behaviour on #88 so instead I decided to clean things up a little.
In this change, I introduce a new `snapshot(spec:name:arguments:congifuration:)` method and called it in every single test method.
```swift
func testEdgecasesRename() throws {
try snapshot(
spec: .edgecases,
name: "edgecases-rename",
arguments: [
"--package", "edgecases-rename"
],
configuration: """
{
"rename": {
"properties": {
"ContainerA.Child.Child.renameMe": "onlyItRenamed"
},
"entities": {
"ApiResponse": "APIResponse",
"Status": "State"
}
}
}
"""
)
}
```
This method then internally handles the `--output` path and adds a temporary …
=> Cleanup tests with new snapshot method

Sources/CreateAPI/Generate.swift, Sources/CreateAPI/Helpers/ConfigFileLocation.swift, Sources/CreateOptions/GenerateOptions.swift, Tests/CreateAPITests/GenerateArgumentTests.swift, Tests/CreateAPITests/GenerateTestCase.swift
- part of #47 
Prior to this change, if you ran the following:
```bash
$ create-api generate --config wrong/path/to/config.yml schema.json
```
The generator would ignore the fact that **wrong/path/to/config.yml** was an invalid path as long as it had the right extension. Instead, it would just revert to using the default config, which might leave the user confused as to why their options aren't being applied. 
It most likely did this because the default value was always set to **.create-api.yaml** and we don't necessarily expect this file to always exist, and we wouldn't want to error if it didn't since the user didn't explicitly define it. 
It was a bit hard to check this in the `Generate` command with the `config` alone since it's just a `String` and Swift Arguments Parser doesn't give …
=> Raise error if `--config` file location does not exist or is not valid

Sources/CreateAPI/Output/OutputWriter.swift
In #117 I accidentally left a print statement whenever we write a file to disk.
=> Stop printing filepaths when writing output

Sources/CreateAPI/Output/Output.swift, Tests/CreateAPITests/GenerateTestCase.swift
- part of #88 
When generating, CreateAPI will nest the generated **Package.swift** (and other files) in side a directory within the output dir. This is inconsistent with how `--module` generation works and results in incorrect usage of the `--output` flag since its expected that the output is an empty directory (for `--clean` to not mistakenly delete non-generated sources).
This change aligns the behaviour between `--package` and `--module` so that all generated contents are located in the root of the `--output` directory. 
There are changes to the snapshot tests here since I'm able to just revert the workaround that we used in the first place.
=> [BREAKING] Generate `--package` directly into `--output`

Tests/CreateAPITests/Compliling/PackageCompiler.swift, Tests/CreateAPITests/Compliling/PackageManifest.swift, Tests/CreateAPITests/GenerateOptionsTests.swift, Tests/CreateAPITests/GenerateTestCase.swift, Tests/CreateAPITests/Snapshotting/Snapshotter.swift, Tests/Support/AllPackages/Package.swift
When we recreate the generator snapshots, if we add a new package we usually have to manually update **Tests/CreateAPITests/AllPackages/Package.swift** so that CI will try and build the package when we create Pull Requests. This was a pain to keep on top of. 
In this change, I update the tests so that they record all of the generated packages and upon completion of the tests, they update the **Package.swift** file. 
It's a little rough and ready, but I didn't want to spend a lot of time refactoring this area although I think that we probably could do. Any suggestions for improvements are welcome.
cc @LePips
=> Automatically update AllPackages bundle when regenerating snapshots

.gitignore, .swiftpm/xcode/xcshareddata/xcschemes/CreateAPI.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/Record Snapshots.xcscheme, Tests/CreateAPITests/Snapshotting/Snapshotter.swift
Until now, I didn't realise that you could still share Xcode schemes when working with Swift Package projects. 
Knowing this means that we can avoid having to modify **Snapshotter.swift** every time that we want to re-record snapshots by instead having a shared scheme that defines the environment variable. 
To achieve this, I updated the **.gitignore** to match one that was produced by running `swift package init` (I added the custom ignore at the end of the file.
cc @LePips
=> Introduce 'Record Snapshots' scheme

Sources/CreateAPI/Generate.swift, Tests/CreateAPITests/GenerateArgumentTests.swift
- closes #88 
Prior to this change, if you ran the generator like this:
```bash
$ create-api generate --config ".create-api.yml" --package "Foo" --output "./" "schema.json" --clean
```
Then you would find that **.create-api.yml** and **schema.json** along with any other files within **./** end up being deleted.
This is not ideal, but its mostly a problem because of how `--package` **use** to work as it nested the output meaning that people were more likely to use **./** as their output directory. We've since solved that inconsistency however and now it's expected that people will use a separate output directory. 
If they don't however, and try using `--clean`, this PR will now cause the generator to error instead.
=> Validate that clean isn't going to delete spec or config file

Sources/CreateAPI/Generate.swift
#101
Prior to this change, if you didn't specify the `--output` directory then your generated sources would be written into the hidden **./.create-api/** directory. 
This is probably a bit confusing and also the format (lower-hyphen-case) doesn't really match styles of typical Swift/Xcode projects.
In this change, I adjust the default to **CreateAPI**, which seems a little more fitting.
=> Change `--output` directory to ./CreateAPI

Docs/ConfigOptions.md, Sources/CreateAPI/Generator/Generator+Schemas.swift, Sources/CreateOptions/ConfigOptions.swift, Tests/CreateAPITests/GenerateOptionsTests.swift
- Closes https://github.com/CreateAPI/CreateAPI/issues/112
Renames property names prior to processing, meaning that they will respect the schema name instead of the final Swift name. Updates the edge case test for proper schema renaming and some other tests that renamed _to_ a Swifty name.
=> `rename.properties` respects schema names

Docs/ConfigOptions.md, Sources/CreateOptions/ConfigOptions.swift, Tests/CreateAPITests/GenerateTests.swift, Tests/Support/Snapshots/edgecases-change-access-control/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-change-access-control/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-coding-keys/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-coding-keys/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-default/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-default/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-disable-acronyms/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-disable-acronyms/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-disable-enums/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-disable-enums/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-indent-with-two-width-spaces/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-indent-with-two-width-spaces/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-int32-int64/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-int32-int64/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-rename-properties/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-rename-properties/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-rename/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-rename/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-tabs/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-tabs/Sources/Entities/Dog.swift, Tests/Support/Snapshots/edgecases-yaml-config/Sources/Entities/Cat.swift, Tests/Support/Snapshots/edgecases-yaml-config/Sources/Entities/Dog.swift
- Closes #63 
Currently CreateAPI takes one of two approaches when dealing with schemas that reference other types using `allOf`:
1. Nest the referenced entity within
2. Inline the properties from the referenced entity
Until this changes, the former was the default behaviour however this behaviour isn't really inline with what you might expect a generator to do and it results in a strangely formed (but functional) entity. 
In the future, we plan to improve the inlining behaviour by adding other alternatives (i.e protocol composition and maybe even class inheritance) but for now we want to change the default behaviour. 
In this PR, I update `isInliningPropertiesFromReferencedSchemas` (now `inlineReferencedSchemas`) so that properties are inlined into the entity by default. 
I also …
=> Change default behaviour of `isInliningPropertiesFromReferencedSchemas` (now `inlineReferencedSchemas`)

Sources/CreateAPI/Generator/Generator+Paths.swift
I noticed that the code to generate paths would only perform parallel generation when `--verbose` was specified. Something that I assume was done during debugging but committed by mistake? 
It's inconsistent with the other implementation so I have instead set this value back to check `arguments.isParallel` instead. The result is that by default, the GitHub spec now generates a bit quicker:
```
$ swift run create-api generate Tests/Support/Specs/github.yaml --config-option module=OctoKit --measure --clean
...
Generate paths completed (0.852 s)
Generating entities completed (0.402 s)
Write output files completed (0.170 s)
Generation completed (2.892 s)
```
```
$ swift run create-api generate Tests/Support/Specs/github.yaml --config-option module=OctoKit --measure --clean
...
Generate paths …
```
=> Run path generation in parallel when specified

Sources/CreateAPI/Generator/Templates.swift, Tests/Support/Snapshots/OctoKit/Sources/Entities/Deployment.swift, Tests/Support/Snapshots/OctoKit/Sources/Entities/Issue.swift, Tests/Support/Snapshots/OctoKit/Sources/Entities/ScimUser.swift, Tests/Support/Snapshots/OctoKit/Sources/Entities/ValidationError.swift, Tests/Support/Snapshots/OctoKit/Sources/Entities/WebhookConfigInsecureSSL.swift, Tests/Support/Snapshots/OctoKit/Sources/Paths/PathsReposWithOwnerWithRepoContentsWithPath.swift, Tests/Support/Snapshots/OctoKit/Sources/Paths/PathsUser.swift, Tests/Support/Snapshots/OctoKit/Sources/Paths/PathsUsersWithUsername.swift, Tests/Support/Snapshots/discriminator/Sources/Entities/AnotherContainer.swift, Tests/Support/Snapshots/discriminator/Sources/Entities/Container.swift, Tests/Support/Snapshots/strip-parent-name-nested-objects-default/Sources/Entities/Container.swift, Tests/Support/Snapshots/strip-parent-name-nested-objects-enabled/Sources/Entities/Container.swift
- #158 
When we faced the linked bug above, it was hard to figure out exactly what was going on at first. The only message that we saw was the following:
> Failed to intialize `oneOf`
It would be nicer if the message logged could help us to understand what has gone on a little more so I have updated it so that it includes more details about the issue. 
You can see the diff of the snapshots for an idea of how this looks.
=> Improve error messages that are used when `oneOf` object decoding fails
